#!/usr/bin/env python3
# -*- coding: utf-8 -*-

text = '182-9134 24 99'
digit_count = sum(c.isdigit() for c in text)
space_count = text.count(' ')
special_count = sum(text.count(c) for c in ['-', '_', '.', '/', '\\', '|'])

print('=' * 80)
print('电话号码分析: 182-9134 24 99')
print('=' * 80)
print(f'  数字数量: {digit_count}')
print(f'  空格数量: {space_count}')
print(f'  特殊字符数量: {special_count}')
print()
print('检测阈值:')
print(f'  空格检测: digitCount > 10 且 spaceCount > digitCount/2')
print(f'  是否触发: {digit_count} > 10 = {digit_count > 10}, {space_count} > {digit_count/2} = {space_count > digit_count/2}')
print(f'  结论: {"[X] 不触发" if not (digit_count > 10 and space_count > digit_count/2) else "[OK] 触发"}')
print()
print(f'  特殊字符检测: digitCount > 8 且 specialCount >= 2')
print(f'  是否触发: {digit_count} > 8 = {digit_count > 8}, {special_count} >= 2 = {special_count >= 2}')
print(f'  结论: {"[X] 不触发" if not (digit_count > 8 and special_count >= 2) else "[OK] 触发"}')

print()
print('=' * 80)
text2 = '6101二52零0503153524'
chinese_nums = ['零', '一', '二', '三', '四', '五', '六', '七', '八', '九']
chinese_count = sum(text2.count(c) for c in chinese_nums)
print('身份证号分析: 6101二52零0503153524')
print('=' * 80)
print(f'  中文数字数量: {chinese_count}')
print()
print('检测阈值:')
print(f'  中文数字检测: chineseCount >= 5')
print(f'  是否触发: {chinese_count} >= 5 = {chinese_count >= 5}')
print(f'  结论: {"[X] 不触发" if chinese_count < 5 else "[OK] 触发"}')
print()
print(f'  同音字检测: homophoneCount >= 3')
print(f'  是否触发: {chinese_count} >= 3 = {chinese_count >= 3}')
print(f'  结论: {"[X] 不触发" if chinese_count < 3 else "[OK] 触发"}')

print()
print('=' * 80)
print('总结')
print('=' * 80)
print('1. 电话号码 "182-9134 24 99":')
print('   - 只有10个数字，不满足空格检测阈值(>10)')
print('   - 只有1个特殊字符，不满足特殊字符检测阈值(>=2)')
print('   - [X] ASDF框架不会触发检测')
print()
print('2. 身份证号 "6101二52零0503153524":')
print('   - 只有2个中文数字，不满足中文数字检测阈值(>=5)')
print('   - 只有2个同音字，不满足同音字检测阈值(>=3)')
print('   - [X] ASDF框架不会触发检测')
print()
print('结论: ASDF框架的检测阈值设置过高，导致这些绕过案例未被检测到！')
print('=' * 80)
