// Command generate_test_data builds the layered-detection evaluation corpus used by
// experiments/scripts/ablation_adversarial_eval.py.
//
// The corpus answers a specific question: can obfuscated or context-ambiguous
// sensitive data still be recognised, without flagging lookalike non-sensitive
// values? Four categories are therefore produced, balanced by construction:
//
//	standard       sensitive values in canonical form          (expected_sensitive = true)
//	bypass_attack  sensitive values deliberately obfuscated    (expected_sensitive = true)
//	confusing      lookalikes that must NOT be flagged         (expected_sensitive = false)
//	normal         ordinary non-sensitive prose                (expected_sensitive = false)
//
// Two properties matter for the numbers to be defensible:
//
//  1. Positive samples are generated by real encoding rules, not typed by hand.
//     Identity cards carry a valid GB 11643-1999 check digit and phone numbers use
//     assigned mobile prefixes, so a detector that validates structure sees the same
//     thing it would see in production. Hand-typed literals with wrong check digits
//     would let a structural validator fail for reasons that have nothing to do with
//     obfuscation.
//  2. Generation is deterministic: the same -seed and -per-category always produce
//     the same bytes, so a dataset digest can be re-derived later.
//
// The output is deliberately separate from test_data_100.json, which historical
// results reference by digest and which this command must not touch.
package main

import (
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
)

// TestCase is the record shape consumed by ablation_adversarial_eval.py.
type TestCase struct {
	ID                int      `json:"id"`
	Content           string   `json:"content"`
	ExpectedSensitive bool     `json:"expected_sensitive"`
	SensitiveTypes    []string `json:"sensitive_types"`
	AttackType        string   `json:"attack_type"`
	Category          string   `json:"category"`
	Description       string   `json:"description"`
}

// categoryOrder fixes the emission order so the file is reproducible.
var categoryOrder = []string{"standard", "bypass_attack", "confusing", "normal"}

// idCardWeights and idCardCheckChars implement the GB 11643-1999 check digit:
// the first 17 digits are weighted, summed, and reduced modulo 11.
var (
	idCardWeights    = []int{7, 9, 10, 5, 8, 4, 2, 1, 6, 3, 7, 9, 10, 5, 8, 4, 2}
	idCardCheckChars = []byte("10X98765432")
)

// administrativeCodes are real division codes, so generated identity numbers are
// shaped like genuine ones rather than like arbitrary six-digit prefixes.
var administrativeCodes = []string{
	"110101", "310115", "440305", "500101", "210102", "330106",
	"420111", "610104", "510107", "320108", "350203", "230103",
}

// mobilePrefixes covers the assigned Chinese mobile ranges used by the corpus.
var mobilePrefixes = []string{
	"138", "139", "150", "151", "158", "159", "170", "178",
	"180", "186", "188", "189", "190", "191", "199", "133",
}

var familyNames = []string{
	"李", "王", "张", "刘", "陈", "杨", "黄", "赵", "周", "吴",
	"徐", "孙", "马", "朱", "胡", "郭", "何", "林", "高", "罗",
}

var givenNames = []string{
	"敏", "秀英", "建国", "桂英", "志强", "淑珍", "海燕", "文军", "小梅", "国庆",
	"玉兰", "春生", "丽华", "永强", "凤英", "德明", "月华", "守义", "素芬", "宝林",
}

var eventTypes = []string{
	"pain", "mood", "vital_signs", "fall", "sleep", "medication", "meal", "confusion",
}

var eventLabels = map[string]string{
	"pain":        "疼痛",
	"mood":        "情绪",
	"vital_signs": "生命体征",
	"fall":        "跌倒",
	"sleep":       "睡眠",
	"medication":  "用药",
	"meal":        "进食",
	"confusion":   "意识模糊",
}

// normalTopics and normalPredicates are combined to produce the ordinary-prose
// category. They are combinatorial so the count can grow without hand-writing
// every sentence; the manifest records that the text is template-derived.
var normalTopics = []string{
	"今天天气", "院内环境", "食堂的饭菜", "活动室的气氛", "图书室的藏书",
	"康复训练室", "护理团队", "家属探视安排", "院内绿化", "手工艺活动",
	"健康讲座", "每日例行查房", "生日会筹备", "院内医务室", "床品更换",
	"营养配餐", "老人作息", "员工培训", "院内监控", "晨间锻炼",
}

var normalPredicates = []string{
	"很好，适合出门散步。",
	"整洁舒适，老人们都很满意。",
	"营养均衡，搭配得很合理。",
	"温馨融洽，老人们有说有笑。",
	"丰富充足，可以自由借阅。",
	"设备齐全，有专业人员指导。",
	"专业细致，服务态度很好。",
	"安排在每天下午两点到五点。",
	"维护得当，四季都有景致。",
	"内容有趣，锻炼动手能力。",
	"通俗实用，老人们听得认真。",
	"按时进行，关注身体状况。",
	"正在有序推进中。",
	"二十四小时都有值班人员。",
	"按时进行，保持卫生整洁。",
	"由营养师按需搭配。",
	"规律有序，晚上九点休息。",
	"定期开展，持证上岗。",
	"运行正常，保障老人安全。",
	"组织有序，参与积极性很高。",
}

type generator struct {
	rng *rand.Rand
}

// identityCard builds an 18-digit identity number with a correct check digit.
func (g *generator) identityCard() string {
	admin := administrativeCodes[g.rng.Intn(len(administrativeCodes))]
	year := 1930 + g.rng.Intn(70)
	month := 1 + g.rng.Intn(12)
	day := 1 + g.rng.Intn(28)
	sequence := 100 + g.rng.Intn(900)
	first17 := fmt.Sprintf("%s%04d%02d%02d%03d", admin, year, month, day, sequence)

	sum := 0
	for index, char := range first17 {
		if char < '0' || char > '9' {
			panic("identity card body must be numeric")
		}
		sum += int(char-'0') * idCardWeights[index]
	}
	return first17 + string(idCardCheckChars[sum%11])
}

// mobileNumber builds an 11-digit number on an assigned prefix.
func (g *generator) mobileNumber() string {
	return fmt.Sprintf("%s%08d", mobilePrefixes[g.rng.Intn(len(mobilePrefixes))], g.rng.Intn(100000000))
}

func (g *generator) medicalRecordNumber() string {
	return fmt.Sprintf("MR%d%05d", 2026, g.rng.Intn(100000))
}

func (g *generator) bloodPressure() string {
	systolic := 100 + g.rng.Intn(60)
	diastolic := 60 + g.rng.Intn(40)
	return fmt.Sprintf("%d/%d", systolic, diastolic)
}

func (g *generator) person() string {
	return familyNames[g.rng.Intn(len(familyNames))] + givenNames[g.rng.Intn(len(givenNames))]
}

func (g *generator) eventType() string {
	return eventTypes[g.rng.Intn(len(eventTypes))]
}

// spacedDigits separates every digit, defeating contiguous-digit patterns.
func spacedDigits(value string) string {
	out := make([]byte, 0, len(value)*2)
	for index := 0; index < len(value); index++ {
		if index > 0 {
			out = append(out, ' ')
		}
		out = append(out, value[index])
	}
	return string(out)
}

// fullWidthDigits maps ASCII digits to their Chinese numeral form.
func fullWidthDigits(value string) string {
	table := map[byte]string{
		'0': "零", '1': "一", '2': "二", '3': "三", '4': "四",
		'5': "五", '6': "六", '7': "七", '8': "八", '9': "九",
	}
	out := ""
	for index := 0; index < len(value); index++ {
		out += table[value[index]]
	}
	return out
}

// homophoneDigits uses the spoken/financial variants that homophone attacks rely on.
func homophoneDigits(value string) string {
	table := map[byte]string{
		'0': "零", '1': "幺", '2': "贰", '3': "叁", '4': "肆",
		'5': "伍", '6': "陆", '7': "柒", '8': "捌", '9': "玖",
	}
	out := ""
	for index := 0; index < len(value); index++ {
		out += table[value[index]]
	}
	return out
}

func encodedDigits(value string) string {
	return base64.StdEncoding.EncodeToString([]byte(value))
}

// separatorFlavoured inserts a rotating separator into a digit run.
func separatorFlavoured(value string, separator byte, group int) string {
	out := make([]byte, 0, len(value)+len(value)/group)
	for index := 0; index < len(value); index++ {
		if index > 0 && index%group == 0 {
			out = append(out, separator)
		}
		out = append(out, value[index])
	}
	return string(out)
}

// plan distributes a category's quota across its sub-types as evenly as possible
// without dropping or over-allocating any sub-type.
func plan(total int, subtypes []string) map[string]int {
	allocation := map[string]int{}
	base := total / len(subtypes)
	remainder := total % len(subtypes)
	for index, subtype := range subtypes {
		allocation[subtype] = base
		if index < remainder {
			allocation[subtype]++
		}
	}
	return allocation
}

func main() {
	perCategory := flag.Int("per-category", 100, "samples per category (standard, bypass_attack, confusing, normal)")
	outPath := flag.String("out", "test_data_400.json", "output dataset path")
	manifestPath := flag.String("manifest", "", "output manifest path; defaults to <out>.manifest.json")
	seed := flag.Int64("seed", 20260920, "deterministic generation seed")
	flag.Parse()

	if *perCategory < len(categoryOrder) {
		fmt.Fprintf(os.Stderr, "-per-category must be at least %d\n", len(categoryOrder))
		os.Exit(2)
	}
	if *manifestPath == "" {
		*manifestPath = *outPath + ".manifest.json"
	}

	g := &generator{rng: rand.New(rand.NewSource(*seed))}
	counts := map[string]int{}
	subtypeCounts := map[string]map[string]int{}

	cases := make([]TestCase, 0, *perCategory*len(categoryOrder))
	nextID := 1

	appendCase := func(content string, sensitive bool, sensitiveTypes []string, attackType, category, subtype, description string) {
		if sensitiveTypes == nil {
			sensitiveTypes = []string{}
		}
		cases = append(cases, TestCase{
			ID:                nextID,
			Content:           content,
			ExpectedSensitive: sensitive,
			SensitiveTypes:    sensitiveTypes,
			AttackType:        attackType,
			Category:          category,
			Description:       description,
		})
		nextID++
		counts[category]++
		if subtypeCounts[category] == nil {
			subtypeCounts[category] = map[string]int{}
		}
		subtypeCounts[category][subtype]++
	}

	// ---------------------------------------------------------------- standard
	standardSubtypes := []string{"id_card", "phone", "medical_record", "blood_pressure"}
	standardPlan := plan(*perCategory, standardSubtypes)
	for subtype, quota := range standardPlan {
		for index := 0; index < quota; index++ {
			switch subtype {
			case "id_card":
				appendCase(fmt.Sprintf("患者身份证：%s", g.identityCard()), true, []string{"id_card"},
					"normal", "standard", subtype, fmt.Sprintf("标准身份证格式（含有效校验位）#%d", index+1))
			case "phone":
				appendCase(fmt.Sprintf("联系电话：%s", g.mobileNumber()), true, []string{"phone"},
					"normal", "standard", subtype, fmt.Sprintf("标准手机号格式 #%d", index+1))
			case "medical_record":
				appendCase(fmt.Sprintf("病历号：%s", g.medicalRecordNumber()), true, []string{"medical_record"},
					"normal", "standard", subtype, fmt.Sprintf("标准病历号格式 #%d", index+1))
			case "blood_pressure":
				appendCase(fmt.Sprintf("血压：%s mmHg", g.bloodPressure()), true, []string{"blood_pressure"},
					"normal", "standard", subtype, fmt.Sprintf("标准血压格式 #%d", index+1))
			}
		}
	}

	// ----------------------------------------------------------- bypass_attack
	bypassSubtypes := []string{"space_separation", "separator", "chinese_number", "homophone", "base64", "semantic"}
	bypassPlan := plan(*perCategory, bypassSubtypes)
	for subtype, quota := range bypassPlan {
		for index := 0; index < quota; index++ {
			switch subtype {
			case "space_separation":
				appendCase(fmt.Sprintf("身份证号：%s", spacedDigits(g.identityCard())), true, []string{"id_card"},
					"space_separation", "bypass_attack", subtype, fmt.Sprintf("空格分隔绕过攻击 #%d", index+1))
			case "separator":
				idCard := g.identityCard()
				phone := g.mobileNumber()
				separators := []byte{'-', '.', '/', '|'}
				separator := separators[index%len(separators)]
				content := separatorFlavoured(phone, separator, 4)
				types := []string{"phone"}
				if index%2 == 0 {
					content = separatorFlavoured(idCard, separator, 6)
					types = []string{"id_card"}
				}
				appendCase(fmt.Sprintf("联系方式：%s", content), true, types,
					"separator", "bypass_attack", subtype, fmt.Sprintf("分隔符混淆攻击 #%d", index+1))
			case "chinese_number":
				appendCase(fmt.Sprintf("证件号码：%s", fullWidthDigits(g.identityCard())), true, []string{"id_card"},
					"chinese_number", "bypass_attack", subtype, fmt.Sprintf("中文数字绕过攻击 #%d", index+1))
			case "homophone":
				appendCase(fmt.Sprintf("身份证：%s", homophoneDigits(g.mobileNumber())), true, []string{"phone"},
					"homophone", "bypass_attack", subtype, fmt.Sprintf("同音字替换攻击 #%d", index+1))
			case "base64":
				appendCase(fmt.Sprintf("编码信息：%s", encodedDigits(g.mobileNumber())), true, []string{"phone"},
					"base64", "bypass_attack", subtype, fmt.Sprintf("Base64编码攻击 #%d", index+1))
			case "semantic":
				person := g.person()
				event := g.eventType()
				templates := []string{
					fmt.Sprintf("%s的证件号码是一%s开头的那个十八位数字", person, homophoneDigits(g.identityCard()[:1])),
					fmt.Sprintf("%s的手机号是%s开头的十一位号码", person, g.mobileNumber()[:3]),
					fmt.Sprintf("%s的病历号是MR开头后面跟着五位数字", person),
					fmt.Sprintf("%s在%s记录中提到的血压是一百二十比八十", person, eventLabels[event]),
					fmt.Sprintf("%s的身份证前六位是%s，后面是出生日期加四位顺序码", person, administrativeCodes[index%len(administrativeCodes)]),
				}
				appendCase(templates[index%len(templates)], true, []string{"id_card", "phone", "medical_record", "blood_pressure"},
					"semantic", "bypass_attack", subtype, fmt.Sprintf("语义描述绕过攻击 #%d", index+1))
			}
		}
	}

	// ---------------------------------------------------------------- confusing
	confusingSubtypes := []string{"postal_code", "employee_id", "order_id", "ratio"}
	confusingPlan := plan(*perCategory, confusingSubtypes)
	for subtype, quota := range confusingPlan {
		for index := 0; index < quota; index++ {
			// Each lookalike reuses the exact shape of a positive sample of the same
			// kind (six digits like an identity prefix, digits/digits like a blood
			// pressure reading) so a detector cannot pass by shape alone.
			switch subtype {
			case "postal_code":
				appendCase(fmt.Sprintf("邮政编码：%s", administrativeCodes[index%len(administrativeCodes)]), false, []string{},
					"normal", "confusing", subtype, fmt.Sprintf("邮编易混淆场景 #%d（应判定为非敏感）", index+1))
			case "employee_id":
				appendCase(fmt.Sprintf("员工工号：EMP%d", 20260000+index), false, []string{},
					"normal", "confusing", subtype, fmt.Sprintf("工号易混淆场景 #%d（应判定为非敏感）", index+1))
			case "order_id":
				appendCase(fmt.Sprintf("订单号：ORD%d", 202600000+index), false, []string{},
					"normal", "confusing", subtype, fmt.Sprintf("订单号易混淆场景 #%d（应判定为非敏感）", index+1))
			case "ratio":
				// A ratio shares the "int/int" shape with blood pressure.
				appendCase(fmt.Sprintf("得分：%d/%d", 100+index, 120+index), false, []string{},
					"normal", "confusing", subtype, fmt.Sprintf("比例易混淆场景 #%d（应判定为非敏感）", index+1))
			}
		}
	}

	// ------------------------------------------------------------------- normal
	for index := 0; index < *perCategory; index++ {
		text := normalTopics[index%len(normalTopics)] + normalPredicates[(index/len(normalTopics)+index)%len(normalPredicates)]
		appendCase(text, false, []string{},
			"normal", "normal", "ordinary_prose", fmt.Sprintf("正常非敏感文本 #%d", index+1))
	}

	// Fail loudly rather than emit a corpus that silently breaks the declared
	// balance: the ablation reports per-category rates, so an unbalanced file
	// would make cross-category comparison meaningless.
	for _, category := range categoryOrder {
		if counts[category] != *perCategory {
			fmt.Fprintf(os.Stderr, "category %s has %d samples, expected %d\n", category, counts[category], *perCategory)
			os.Exit(1)
		}
	}

	payload, err := json.MarshalIndent(cases, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal dataset: %v\n", err)
		os.Exit(1)
	}
	payload = append(payload, '\n')
	if directory := filepath.Dir(*outPath); directory != "." {
		if err := os.MkdirAll(directory, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "create output directory: %v\n", err)
			os.Exit(1)
		}
	}
	if err := os.WriteFile(*outPath, payload, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write dataset: %v\n", err)
		os.Exit(1)
	}

	digest := sha256.Sum256(payload)
	sensitive := 0
	for _, item := range cases {
		if item.ExpectedSensitive {
			sensitive++
		}
	}
	orderedSubtypes := map[string]map[string]int{}
	for _, category := range categoryOrder {
		orderedSubtypes[category] = subtypeCounts[category]
	}
	manifest := map[string]interface{}{
		"schema":              "adversarial-sensitive-data-manifest-v1",
		"generator":           "scripts/go/generate_test_data.go",
		"generation_method":   "deterministic template amplification with real encoding rules",
		"seed":                *seed,
		"per_category":        *perCategory,
		"total_samples":       len(cases),
		"sensitive_samples":   sensitive,
		"benign_samples":      len(cases) - sensitive,
		"category_counts":     counts,
		"subtype_counts":      orderedSubtypes,
		"dataset_path":        *outPath,
		"dataset_sha256":      hex.EncodeToString(digest[:]),
		"dataset_schema_note": "JSON array of {id, content, expected_sensitive, sensitive_types, attack_type, category, description}",
		"known_limits": []string{
			"Text is template-derived, so lexical diversity is lower than a human-authored corpus.",
			"The four categories are balanced by construction; real traffic is not.",
			"Positive identity numbers carry valid GB 11643-1999 check digits, but they are synthetic and do not correspond to real people.",
		},
	}
	// Marshal the manifest with sorted keys for a stable digest.
	manifestBytes, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal manifest: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*manifestPath, append(manifestBytes, '\n'), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write manifest: %v\n", err)
		os.Exit(1)
	}

	keys := make([]string, 0, len(counts))
	for category := range counts {
		keys = append(keys, category)
	}
	sort.Strings(keys)
	fmt.Printf("dataset=%s\n", *outPath)
	fmt.Printf("manifest=%s\n", *manifestPath)
	fmt.Printf("total_samples=%d sensitive=%d benign=%d\n", len(cases), sensitive, len(cases)-sensitive)
	for _, category := range keys {
		fmt.Printf("  %s: %d\n", category, counts[category])
	}
	fmt.Printf("sha256=%s\n", hex.EncodeToString(digest[:]))
}
